```{r}
#first library a few packages that we will use during the practical
#note you may need to install them first...
library(spatstat)#空间点模式分析
library(here)
library(sp)#定义了点（Points）、线（Lines）和多边形（Polygons）等空间数据的类和方法
library(tmap)
library(sf)#基于“Simple Features”标准
library(tmaptools)
```

```{r}
##First, get the London Borough Boundaries获取伦敦边界
LondonBoroughs <- st_read(here::here("practical_6", "statistical-gis-boundaries-london", "ESRI", "London_Borough_Excluding_MHW.shp"))
```
```{r}
library(stringr)#提供了一组用于字符串处理的函数
#dplyr 包的 filter 函数对数据进行过滤
#str_detect(GSS_CODE, "^E09")：检查 GSS_CODE 列中是否有以 E09 开头的值
BoroughMap <- LondonBoroughs %>%
  dplyr::filter(str_detect(GSS_CODE, "^E09"))%>%
  st_transform(., 27700)
#. 是管道操作符传递过来的数据（即过滤后的 BoroughMap）

#快速生成地图
qtm(BoroughMap)
```
```{r}
summary(BoroughMap)
```
```{r}
BluePlaques <- st_read(here::here("practical_6",
                                  "open-plaques-london-2018-04-08.geojson")) %>%
  st_transform(.,27700)
```
```{r}
summary(BluePlaques)
```
```{r}
# plot the blue plaques斑块 in the city

# 设置 tmap 的模式为静态绘图模式（plot）
tmap_mode("plot")
# 定义地图的第一层，BoroughMap 是一个包含伦敦行政区几何形状的空间对象（通常是 sf 数据对象）
# col = NA: 不填充多边形内部（透明填充），alpha = 0.5: 设置多边形的透明度为 50%
# 定义地图的第二层，数据源为 BluePlaques
# 在地图上绘制点符号
tm_shape(BoroughMap) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(BluePlaques) +
  tm_dots(col = "blue")
```
```{r}
# 数据清洗
#remove duplicates
library(tidyverse)
library(sf)

# 使用 distinct() 函数移除 BluePlaques 数据集中的重复行
BluePlaques <- distinct(BluePlaques)
```
```{r}
# 空间子集操作，使用 BoroughMap 的几何边界对 BluePlaques 进行裁剪或筛选
BluePlaquesSub <- BluePlaques[BoroughMap,]
#check to see that they've been removed
# 将 tmap 设置为静态模式
tmap_mode("plot")

tm_shape(BoroughMap) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(BluePlaquesSub) +
  tm_dots(col = "blue")
```

```{r}
# add sparse=false to get the complete matrix.添加 sparse = FALSE 参数以获得完整的矩阵
# st_intersects(BoroughMap, BluePlaques)该函数用于判断 BoroughMap 中的几何形状是否与 BluePlaques 中的几何形状相交
intersect_indices <-st_intersects(BoroughMap, BluePlaques)
```

```{r}
Londonborough <- st_read(here::here("Practical_6",
                                    "statistical-gis-boundaries-london", 
                                    "ESRI", 
                                    "London_Borough_Excluding_MHW.shp"))%>%
  st_transform(., 27700)
```
```{r}
OSM <- st_read(here::here("practical_6",
                          "greater-london-latest-free.shp", 
                          "gis_osm_pois_a_free_1.shp")) %>%
  st_transform(., 27700) %>%
  #select hotels only
  filter(fclass == 'hotel')
```
```{r}
# st_join空间连接
# 根据空间关系（默认为相交 intersect）将 Londonborough 的属性合并到 OSM 数据中
# 如果 OSM 中的一个特征与多个 Londonborough 的特征相交，该特征会被复制多次，每次附加一个匹配的属性
join_example <-  st_join(OSM, Londonborough)

#返回 join_example 数据集中的行数
nrow(join_example)
```

```{r}
#London Borough data is already in 277000
Londonborough <- st_read(here::here("practical_6",
                                    "statistical-gis-boundaries-london", 
                                    "ESRI", 
                                    "London_Borough_Excluding_MHW.shp"))%>%
  st_transform(., 27700)
```
```{r}
# read in the .csv
# and make it into spatial data

# 使用 sf 包中的 st_as_sf() 函数将普通数据帧转换为 sf 对象（即空间数据帧）
# 指定 "longitude" 和 "latitude" 作为几何列，并设置坐标参考系统（CRS）为 EPSG:4326 (WGS84 地理坐标)
# 将空间数据转换为 EPSG:27700（英国国家网格）
Airbnb <- read_csv("practical_6/listings.csv") %>%
  st_as_sf(., coords = c("longitude", "latitude"), 
                   crs = 4326) %>%
    st_transform(., 27700)%>%
    #select entire places that are available all year 筛选数据，仅保留类型为 'Entire home/apt' 的 Airbnb 房源，并且这些房源全年 365 天可用
    filter(room_type == 'Entire home/apt' & availability_365 =='365')


# make a function for the join
# functions are covered in practical 7
# but see if you can work out what is going on
# hint all you have to do is replace data1 and data2 提示你所要做的就是替换 data1 和 data2
# with the data you want to use

Joinfun <- function(data1, data2){

# data1 %>% st_join(Londonborough, .)：使用 st_join() 函数将 data1 和 Londonborough 进行空间连接
# add_count() 函数用于对每个 GSS_CODE 的酒店数量进行计数，并将结果添加为名为 "hotels_in_borough" 的新列
output<- data1%>%
  st_join(Londonborough,.) %>%
  add_count(GSS_CODE, name="hotels_in_borough") 

  return(output)
}

#Hotels： 处理 OSM 数据，加入到 Londonborough。
#Airbnb： 处理 Airbnb 数据，同样加入到 Londonborough
Hotels <- Joinfun(OSM, Londonborough)
Airbnb <- Joinfun(Airbnb, Londonborough)
 
# 对 Hotels 数据集按照 GSS_CODE 和 NAME 进行分组
#对每个分组内的数据进行汇总，提取每个行政区中唯一的酒店数量，生成新的列 Accomodation count，表示该行政区的酒店或住宿设施总数。
Hotels <- Hotels %>%
  #at the moment each hotel is a row for the borough
  #we just one one row that has number of airbnbs
  group_by(., GSS_CODE, NAME)%>%
  summarise(`Accomodation count` = unique(hotels_in_borough))


Airbnb <- Airbnb %>%
  group_by(., GSS_CODE, NAME)%>%
  summarise(`Accomodation count` = unique(hotels_in_borough))
```
```{r}
all_accomodation <- st_join(Hotels, Airbnb)

head(all_accomodation)
```
```{r}
all_accomodation <- st_join(Hotels, Airbnb, join = st_equals)

head(all_accomodation)
```
#study area
```{r}
#extract the borough

# select by attribute根据属性选择Harrow生成新空间数据集
Harrow <- BoroughMap %>%
  filter(., NAME=="Harrow")

#Check to see that the correct borough has been pulled out
tm_shape(Harrow) +
  tm_polygons(col = NA, alpha = 0.5)
```
```{r}
#clip the data to our single borough在 BluePlaques 中筛选出那些几何形状与 Harrow 区域相交的行。保留所有的列。
BluePlaquesSub <- BluePlaques[Harrow,]
#check that it's worked
tmap_mode("plot")
```
```{r}
tm_shape(Harrow) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(BluePlaquesSub) +
  tm_dots(col = "blue")
```

```{r}
#now set a window as the borough boundary建一个观测窗口
window <- as.owin(Harrow)
plot(window)
```
```{r}
# create a sp object创建一个点模式对象来分析点模式
# 使用 as() 函数将 sf 对象 BluePlaquesSub 转换为 Spatial 对象
BluePlaquesSub<- BluePlaquesSub %>%
  as(., 'Spatial')
# create a ppp object
# 使用 spatstat 包中的 ppp() 函数，将点数据转换为点模式对象，用于点模式分析，X 坐标（经度）， Y 坐标（纬度）
# @coords是 SpatialPointsDataFrame 对象的属性，存储点的坐标矩阵
BluePlaquesSub.ppp <- ppp(x=BluePlaquesSub@coords[,1],
                          y=BluePlaquesSub@coords[,2],
                          window=window)
```
```{r}
# 16为实心圆，cex设置点的大小缩放比例为 0.5，main标题
BluePlaquesSub.ppp %>%
  plot(.,pch=16,cex=0.5, 
       main="Blue Plaques Harrow")
```
#Kernel Density Estimation
```{r}
#使用density()函数从 ppp 对象生成内核密度估计 (KDE) 映射
#西格玛值设置内核的直径
BluePlaquesSub.ppp %>%
  density(., sigma=500) %>%
  plot()
```
#Quadrat Analysis
```{r}
#First plot the points
#16为实心圆，cex设置点的大小缩放比例为 0.5，main标题
plot(BluePlaquesSub.ppp,
     pch=16,
     cex=0.5, 
     main="Blue Plaques in Harrow")

#now count the points in that fall in a 6 x 6，对研究区域进行 6×6 网格划分，统计每个网格内的点数，并将统计结果绘制在已有图形上（add=T 表示叠加）
#grid overlaid across the windowBluePlaquesSub.ppp2<-BluePlaquesSub.ppp %>%
BluePlaquesSub.ppp %>%
  quadratcount(.,nx = 6, ny = 6)%>%
    plot(., add=T, col="red")
```

```{r}
#Qcount 是一个数据框，包含以下两列：①Freq：网格中点的数量。②Freqquadratcount：具有相同点数量的网格数量
#run the quadrat count
#as.data.frame()将 quadratcount 对象转换为数据框格式
#dplyr::count() 函数，计算每种网格点数（Freq）出现的次数
#Var1 和 Var2：表示网格的行号和列号；Var1=Freq：指定以网格点数（Freq）为统计对象
#结果是一个包含两列的数据框：
#第一列：网格中点的数量（Freq）。
#第二列：具有相同点数量的网格个数（n）。
#将列名 n 重命名为 Freqquadratcount
Qcount <- BluePlaquesSub.ppp %>%
  quadratcount(.,nx = 6, ny = 6) %>%
  as.data.frame() %>%
  dplyr::count(Var1=Freq)%>%
  dplyr::rename(Freqquadratcount=n)

#检查第一列中的数据类型 - 如果它是因子，我们需要将其转换为数字
Qcount %>% 
  summarise_all(class)
```
#泊松分布计算预期 k 是一个正方形中蓝色斑块的数量
```{r}
sums <- Qcount %>%
  #calculate the total blue plaques (Var * Freq)
  mutate(total = Var1 * Freqquadratcount) %>%
  dplyr::summarise(across(everything(), sum))%>%
  dplyr::select(-Var1) 

lambda<- Qcount%>%
  #calculate lambda
  mutate(total = Var1 * Freqquadratcount)%>%
  dplyr::summarise(across(everything(), sum)) %>%
  mutate(lambda=total/Freqquadratcount) %>%
  dplyr::select(lambda)%>%
  pull(lambda)
```

```{r}
QCountTable <- Qcount %>%
  mutate(Pr=((lambda^Var1)*exp(-lambda))/factorial(Var1))%>%
  #now calculate the expected counts based on our total number of plaques
  #and save them to the table
  mutate(Expected= (round(Pr * sums$Freqquadratcount, 0)))

#Compare the frequency distributions of the observed and expected point patterns
plot(c(1,5),c(0,14), type="n",
xlab="Number of Blue Plaques (Red=Observed,Blue=Expected)", 
     ylab="Frequency of Occurances")
points(QCountTable$Freqquadratcount, 
       col="Red", 
       type="o", 
       lwd=3)
points(QCountTable$Expected, col="Blue", 
       type="o", 
       lwd=3)
```

#使用卡方检验来比较每个象限的观察频率和预期频率（而不是象限计数的
#卡方检验确定两个分类变量之间是否存在关联。卡方值越高，差异越大。
```{r}
teststats <- quadrat.test(BluePlaquesSub.ppp, nx = 6, ny = 6)
```
```{r}
plot(BluePlaquesSub.ppp,pch=16,cex=0.5, main="Blue Plaques in Harrow")
plot(teststats, add=T, col = "red")
```



#解决样方分析局限性：
#Ripley 的 K 函数的计算内容：将观察到的点分布与整个不同距离半径范围的泊松随机模型进行比较
```{r}
K <- BluePlaquesSub.ppp %>%
  Kest(., correction="border") %>%
  plot()
```

```{r}
Kval <- as.data.frame(Kest(BluePlaquesSub.ppp, correction = "Ripley"))
```

#基于密度的噪声应用空间聚类：DBSCAN
```{r}
library(fpc)
```
#对我所在行政区的蓝色斑块进行 DBSCAN 分析，以查看是否存在任何集群
```{r}
#first check the coordinate reference system of the Harrow spatial polygon:
st_geometry(BoroughMap)
```






